final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mvc.urls')),
    path('api/', include('api.urls')),
]

# Serve static files in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve media files in production
if not settings.DEBUG:
    urlpatterns += [
        path('media/<path>', serve, {'document_root': settings.MEDIA_ROOT}),
        path('static/<path>', serve, {'document_root': settings.STATIC_ROOT}),
    ]

core/models/cart.py
from django.db import models
from .product import Product, Variantion
from .user import Account


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variantions = models.ManyToManyField(Variantion, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.product_name

    def sub_total(self):
        return self.product.price * self.quantity

core/models/product.py
from django.db import models
from .category import Category
from django.urls import reverse
from django.db.models import Avg, Count
from .user import Account


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products', blank=True)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def average_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def count_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def save(self, *args, **kwargs):
        super(Product, self).save(*args, **kwargs)


variant_category_choices = (
    ('color', 'color'),
    ('size', 'size'),
)


class VariantionManager(models.Manager):
    def colors(self):
        return super(VariantionManager, self).filter(variantion_category='color', is_active=True)

    def sizes(self):
        return super(VariantionManager, self).filter(variantion_category='size', is_active=True)


class Variantion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variantion_category = models.CharField(
        max_length=100, choices=variant_category_choices)
    variantion_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariantionManager()

    def __str__(self):
        return self.product.product_name


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

core/models/store.py
from django.db import models


class LocalBranch(models.Model):
    company_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    activate = models.BooleanField(default=False)

    def __str__(self):
        return self.company_name

mvc/views/cart.py
from django.shortcuts import render, get_object_or_404, redirect
from core.models import *
from core.utils import get_cart_id
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required


def cart(request):
    cart_items = CartItem.objects.none()
    try:
        total = 0
        quantity = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart_id = get_cart_id(request)
            cart = Cart.objects.get(cart_id=cart_id)
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
    except Exception:
        pass
    tax = int((2 * total) / 100)
    grand_total = total + tax
    context = {'total': total, 'quantity': quantity,
               'cart_items': cart_items, 'tax': tax, 'grand_total': grand_total}
    return render(request, 'store/cart.html', context)


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    if current_user.is_authenticated:
        product_variantions = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variantion = Variantion.objects.get(
                        variantion_category__iexact=key, variantion_value__iexact=value, product=product)
                    product_variantions.append(variantion)
                except:
                    pass
        cart_item_exists = CartItem.objects.filter(
            user=current_user, product=product).exists()
        if cart_item_exists:
            cart_item = CartItem.objects.filter(
                user=current_user, product=product)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variantions.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            if product_variantions in ex_var_list:
                index = ex_var_list.index(product_variantions)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    cart=cart, product=product, quantity=1)
                item.save()
                if len(product_variantions) > 0:
                    item.variantions.clear()
                    item.variantions.set(set(product_variantions))
                    item.save()
        else:
            try:
                cart_id = get_cart_id(request)
                cart = Cart()
                cart.cart_id = cart_id
                cart.save()
            except:
                cart = Cart.objects.filter(cart_id=cart_id).last()
            cart_item = CartItem.objects.create(
                product=product, quantity=1, cart=cart, user=current_user)
            cart_item.save()
            if len(product_variantions) > 0:
                cart_item.variantions.set(set(product_variantions))
            cart_item.save()
        return redirect('cart')
    else:
        product_variantions = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variantion = Variantion.objects.get(
                        variantion_category__iexact=key, variantion_value__iexact=value, product=product)
                    product_variantions.append(variantion)
                except:
                    pass
        try:
            cart = Cart.objects.get(cart_id=get_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=get_cart_id(request)
            )
            cart.save()
        cart_item_exists = CartItem.objects.filter(
            cart=cart, product=product).exists()
        if cart_item_exists:
            cart_item = CartItem.objects.filter(cart=cart, product=product)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variantions.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            if product_variantions in ex_var_list:
                index = ex_var_list.index(product_variantions)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    cart=cart, product=product, quantity=1)
                item.save()
                if len(product_variantions) > 0:
                    item.variantions.clear()
                    item.variantions.set(set(product_variantions))
                    item.save()
        else:
            cart_item = CartItem.objects.create(
                cart=cart, product=product, quantity=1)
            cart_item.save()
            if len(product_variantions) > 0:
                cart_item.variantions.set(set(product_variantions))
            cart_item.save()
        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    product = Product.objects.get(id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=get_cart_id(request))
            cart_item = CartItem.objects.get(
                cart=cart, product=product, id=cart_item_id)
    except:
        pass
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = Product.objects.get(id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(
            user=request.user, product=product, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
        cart_item = CartItem.objects.get(
            cart=cart, product=product, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


@login_required(login_url='login')
def checkout(request):
    try:
        total = 0
        quantity = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart_id = get_cart_id(request)
            cart = Cart.objects.get(cart_id=cart_id)
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
    except Exception:
        pass
    tax = int((2 * total) / 100)
    grand_total = total + tax
    context = {'total': total, 'quantity': quantity,
               'cart_items': cart_items, 'tax': tax, 'grand_total': grand_total}
    return render(request, 'store/checkout.html', context)

mvc/views/store.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from core.models import *
from core.utils import get_cart_id
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from mvc.form import ReviewForm


def store(request, category_slug=None):
    if category_slug:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(
            category=categories, is_available=True)
        paginator = Paginator(products, 1)
        page = request.GET.get('page', 1)
        paged_products = paginator.get_page(page)
    else:
        products = Product.objects.filter(is_available=True)
        paginator = Paginator(products, 3)
        page = request.GET.get('page', 1)
        paged_products = paginator.get_page(page)
    context = {'products': paged_products, 'product_count': products.count()}
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(
            slug=product_slug, category__slug=category_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=get_cart_id(
            request), product=single_product).exists()
    except Exception as e:
        raise e
    if request.user.is_authenticated:
        try:
            order_product = OrderProduct.objects.filter(user=request.user, product=single_product).exists()
        except Exception:
            order_product = None
    else:
        order_product = None

    product_gallery = ProductGallery.objects.filter(product=single_product)
    reviews = ReviewRating.objects.filter(product=single_product, status=True)
    context = {
        'product': single_product,
        'in_cart': in_cart,
        'ordered': order_product,
        'reviews': reviews,
        'product_gallery': product_gallery
    }
    return render(request, 'store/product_detail.html', context)


def search(request):
    products = Product.objects.all()
    if 'keyword' in request.GET:
        keyword = request.GET.get('keyword')
        if keyword:
            products = products.filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword)).order_by('-created_date')
    context = {'products': products, 'product_count': products.count()}
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        try:
            review = ReviewRating.objects.get(user=request.user, product__id=product_id)
            form = ReviewForm(request.POST)
            review.subject = form.cleaned_data['subject']
            review.rating = form.cleaned_data['rating']
            review.review = form.cleaned_data['review']
            review.save()
            messages.success(request, 'Cảm ơn! Đánh giá của bạn đã được ghi nhận.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                print("valid")
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.status = True
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Cảm ơn! Đánh giá của bạn đã được gửi.')
                return redirect(url)

templates/store/product_detail.html
{%extends 'base.html'%} {% load static %} {%block content%}
<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap main-image">
                            <center><a href="#"><img src="{{product.image.url}}"/></a></center>
                        </div>
                        <!-- img-big-wrap.// -->
                    </article>
                    <!-- gallery-wrap .end// -->
                    <ul class="thumb">
                        <li>
                            <a href="{{product.image.url}}" target="main-image"><img src="{{product.image.url}}"/></a>
                            {% for image in product_gallery %}
                            <a href="{{image.image.url}}" target="main-image">
                                <img src="{{image.image.url}}" alt="Product Image">
                            </a>
                            {% endfor %}
                        </li>
                    </ul>
                </aside>
                <main class="col-md-6 border-left">
                    <form action="{% url 'add_cart' product.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">
                            <h2 class="title">{{product.product_name}}</h2>
                            <div class="rating-star">

                                <span>
                                    <i class="fa fa-star{% if product.average_review < 0.5 %}-o{% elif product.average_review < 1 %}-half-o{%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 1.5 %}-o{% elif product.average_review < 2 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 2.5 %}-o{% elif product.average_review < 3 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 3.5 %}-o{% elif product.average_review < 4 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 4.5 %}-o{% elif product.average_review < 5 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                <span>{{product.count_review}} lượt đánh giá</span>

                                </span>
                            </div>

                            <div class="mb-3">
                                <var class="price h4">{{product.price}}</var>
                            </div>
                            <p>{{product.description}}</p>
                            <hr/>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Color</h6>
                                    <select name="color" class="form-control" id="color" required>
                                        <option value="" disabled selected>Select</option>
                                        {% for i in product.variantion_set.colors %}
                                        <option value="{{i.variantion_value | lower }}">{{i.variantion_value | capfirst}}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <!-- row.// -->
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Select Size</h6>
                                    <select name="size" class="form-control" id="size">
                                        <option value="" disabled selected>Select</option>
                                        {% for i in product.variantion_set.sizes %}
                                        <option value="{{i.variantion_value | lower}}">{{i.variantion_value | capfirst}}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <!-- row.// -->
                            <hr/>
                            {% if product.stock <= 0 %}
                            <h5 class="text-danger">Hết hàng</h5>
                            {%else%}
                            <button type="submit" class="btn btn-primary">
                                <span class="text">Thêm vào giỏ hàng</span>
                                <i class="fas fa-shopping-cart"></i>
                            </button>

                            {%endif%}
                        </article>
                    </form>
                    <!-- product-info-aside .// -->
                </main>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

        <br/>

        <div class="row">
            <div class="col-md-9">


                <form action="{% url 'submit_review' product.id %}" method="POST">
                    {% csrf_token %}
                    <h5>Đánh giá sản phẩm</h5>
                    <div>
                        <!--Rating stars-->
                        <label>Đánh giá của bạn về sản phẩm này?</label>
                        <br>
                        <div class="rate">
                            <input type="radio" name="rating" id="rating10" value="5" required/><label for="rating10"
                                                                                                       title="5"></label>
                            <input type="radio" name="rating" id="rating9" value="4.5" required/><label for="rating9"
                                                                                                        title="4.5"
                                                                                                        class="half"></label>
                            <input type="radio" name="rating" id="rating8" value="4" required/><label for="rating8"
                                                                                                      title="4"></label>
                            <input type="radio" name="rating" id="rating7" value="3.5" required/><label for="rating7"
                                                                                                        title="3.5"
                                                                                                        class="half"></label>
                            <input type="radio" name="rating" id="rating6" value="3" required/><label for="rating6"
                                                                                                      title="3"></label>
                            <input type="radio" name="rating" id="rating5" value="2.5" required/><label for="rating5"
                                                                                                        title="2.5"
                                                                                                        class="half"></label>
                            <input type="radio" name="rating" id="rating4" value="2" required/><label for="rating4"
                                                                                                      title="2"></label>
                            <input type="radio" name="rating" id="rating3" value="1.5" required/><label for="rating3"
                                                                                                        title="1.5"
                                                                                                        class="half"></label>
                            <input type="radio" name="rating" id="rating2" value="1" required/><label for="rating2"
                                                                                                      title="1"></label>
                            <input type="radio" name="rating" id="rating1" value="0.5" required/><label for="rating1"
                                                                                                        title="0.5"
                                                                                                        class="half"></label>
                        </div>
                        <br>
                        Tiêu đề:
                        <input type="text" class="form-control" name="subject" required>
                        <br>
                        Nội dung đánh giá:
                        <textarea name="review" class="form-control" rows="4" required></textarea>
                        <br>
                        {% if request.user.is_authenticated %}
                        {% if ordered %}
                        <input type="submit" value="Gửi" class="btn btn-primary">
                        {% else %}
                        <p>Bạn phải mua hàng trước khi đánh giá</p>
                        {% endif %}
                        {% else %}
                        <p>Bạn phải để  <span><a href="{% url 'login' %}">đăng nhập</a></span> giá sản phẩm
                        </p>
                        {% endif %}
                    </div>
                    {% include 'includes/alert.html' %}
                </form>
                <br>

                <header class="section-heading">
                    <h3>Đánh giá của khách hàng</h3>
                    <div class="rating-star">

                                <span>
                                    <i class="fa fa-star{% if product.average_review < 0.5 %}-o{% elif product.average_review < 1 %}-half-o{%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 1.5 %}-o{% elif product.average_review < 2 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 2.5 %}-o{% elif product.average_review < 3 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 3.5 %}-o{% elif product.average_review < 4 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if product.average_review < 4.5 %}-o{% elif product.average_review < 5 %}-half-o {%else%}{%endif%}"
                                       aria-hidden="true"></i>
                                <span>{{product.count_review}} lượt đánh giá</span>

                                </span>
                    </div>

                </header>
                {% for review in reviews %}
                <article class="box mb-3">
                    <div class="icontext w-100">
                        <div class="text">
                            <span class="date text-muted float-md-right">{{review.updated_at}}</span>
                            <h6 class="mb-1">{{review.user.full_name}}</h6>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {%endif%}"
                                       aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {%endif%}"
                                       aria-hidden="true"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <!-- icontext.// -->
                    <div class="mt-3">
                        <h4>{{review.subject}}</h4>
                        <p>
                            {{review.review}}
                        </p>
                    </div>
                </article>
                {% endfor %}
            </div>
            <!-- col.// -->
        </div>
        <!-- row.// -->
    </div>
    <!-- container .//  -->
</section>
{%endblock%}